/*
 * Script para ata de resultados finais 
 * @param SPERLETIVO_M				Periodo letivo
 * @param CODCOLIGADA_N			  Código da coligada
 * @param CODFILIAL_N         Filial
 * @param CODETAPA_N          Código da etapa
 *
 * @author  Marcelo Valvassori Bittencourt
 * @mail	webmaster@pallottism.com.br
 * @version 1.0 bitts 17/04/2017
 * 
*/


DECLARE @SPERLETIVO_M VARCHAR(10) = '2016';
DECLARE @CODCOLIGADA_N INT = 3;
DECLARE @CODFILIAL_N INT = '6';
DECLARE @CODETAPA_N VARCHAR = '9';


WITH MAPA_FALTAS AS (
	SELECT 
		ETAPA.DESCJUNTODELEG, 
		ETAPA.DESCDELEGACIA,	
		GCOLIGADA.NOME AS MANTENEDORA,
		GFILIAL.RUA + ', ' + GCOLIGADA.NUMERO AS ENDERECO,
		GFILIAL.BAIRRO,
		GFILIAL.CEP,
		GFILIAL.CIDADE,
		GFILIAL.TELEFONE,
		SMATRICPL.NUMALUNO, 
		SALUNO.RA,
		PPESSOA.NOME,
		SMATRICPL.CODSTATUS,
		STM.DESCRICAO AS SITUACAO_MATRICULA,
		SGRADE.DESCRICAO AS NIVEL_ENSINO,		
		ETAPA.DIASLETIVOS,
		CONVERT(INT, ETAPA.CARGAHORARIA) AS CARGAHORARIA,
		CHT.HORAS_AULA AS CARGA_HORARIA_PADRAO,
		CASE 
			WHEN STURNO.TIPO = 'I' THEN 'Integral'
			WHEN STURNO.TIPO = 'M' THEN 'Manhã'	
			WHEN STURNO.TIPO = 'N' THEN 'Noite'
			WHEN STURNO.TIPO = 'V' THEN 'Tarde'
		END AS TURNO,
		ETAPA.CODCOLIGADA,
		ETAPA.CODFILIAL,
		ETAPA.IDPERLET,
		ETAPA.SPERLETIVO,
		ETAPA.CODTURMA,
		ETAPA.AULASDADAS,
		ETAPA.HORAS_AULA,
		ETAPA.NOMEDISCIPLINA,
		ETAPA.CODETAPA,
		ETAPA.DESCRICAO AS DESCRICAOETAPA,
		ETAPA.TIPOETAPA,
		ETAPA.NOTAFALTA,
		SHABILITACAO.CODHABILITACAO,
		SHABILITACAO.CODCURSOHIST,
		SHABILITACAO.NOME AS NOME_SERIE,
		SMATRICPL.CODSTATUSRES,
		ISNULL( SSTATUS.DESCRICAO, STM.DESCRICAO ) AS SITUACAO_FINAL
	FROM
		PPESSOA (NOLOCK)
		LEFT JOIN SALUNO (NOLOCK) ON 
			SALUNO.CODPESSOA = PPESSOA.CODIGO
		LEFT JOIN SMATRICPL (NOLOCK) ON
			SMATRICPL.CODCOLIGADA = SALUNO.CODCOLIGADA 
			AND SMATRICPL.RA = SALUNO.RA			
		LEFT JOIN GCOLIGADA (NOLOCK) ON
			GCOLIGADA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
		LEFT JOIN GFILIAL (NOLOCK) 
			ON GFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
			AND GFILIAL.CODFILIAL = SMATRICPL.CODFILIAL
		LEFT JOIN SSTATUS (NOLOCK) 
			ON SMATRICPL.CODCOLIGADA = SSTATUS.CODCOLIGADA 
			AND SMATRICPL.CODSTATUSRES = SSTATUS.CODSTATUS 
		LEFT JOIN SSTATUS AS STM (NOLOCK) 
			ON SMATRICPL.CODCOLIGADA = STM.CODCOLIGADA 
			AND SMATRICPL.CODSTATUS = STM.CODSTATUS 
		LEFT JOIN SHABILITACAOFILIAL (NOLOCK)
			ON SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
		LEFT JOIN STURNO (NOLOCK) ON
			STURNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
			AND STURNO.CODFILIAL = SHABILITACAOFILIAL.CODFILIAL
			AND SHABILITACAOFILIAL.CODTURNO = STURNO.CODTURNO 
			AND STURNO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO 	
		LEFT JOIN SHABILITACAO (NOLOCK)
			ON SHABILITACAOFILIAL.CODCURSO = SHABILITACAO.CODCURSO
			AND SHABILITACAOFILIAL.CODHABILITACAO = SHABILITACAO.CODHABILITACAO
		LEFT JOIN SGRADE (NOLOCK) 
			ON SGRADE.CODCOLIGADA = SMATRICPL.CODCOLIGADA
			AND SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
			AND SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
			AND SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO	
		
		LEFT JOIN (
			SELECT 
				STURMADISC.CODFILIAL, STURMADISC.CODCOLIGADA, STURMADISC.IDPERLET, STURMADISC.CODTURMA, SUM(SDISCGRADE.CH) AS HORAS_AULA
			FROM 
				STURMADISC (NOLOCK)
				LEFT JOIN SHABILITACAOFILIAL (NOLOCK) ON
					SHABILITACAOFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA AND
					SHABILITACAOFILIAL.CODFILIAL = STURMADISC.CODFILIAL AND
					SHABILITACAOFILIAL.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
				LEFT JOIN SDISCGRADE (NOLOCK) ON
					SDISCGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO AND
					SDISCGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE AND
					SDISCGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND
					SDISCGRADE.CODDISC = STURMADISC.CODDISC AND
					SDISCGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
			
			GROUP BY STURMADISC.CODFILIAL, STURMADISC.CODCOLIGADA, STURMADISC.IDPERLET, STURMADISC.CODTURMA
		) CHT (CODFILIAL, CODCOLIGADA, IDPERLET, CODTURMA, HORAS_AULA ) ON
			CHT.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND
			CHT.CODFILIAL = SMATRICPL.CODFILIAL AND
			CHT.CODTURMA = SMATRICPL.CODTURMA AND 
			CHT.IDPERLET = SMATRICPL.IDPERLET 		
		LEFT JOIN (
			SELECT 
				STURMADISC.CODCOLIGADA, 
				SFILIAL.DESCJUNTODELEG, 
				SFILIAL.DESCDELEGACIA, 
				STURMADISC.IDTURMADISC,
				STURMADISC.CODFILIAL,
				STURMADISC.CODTURMA,
				STURMADISC.IDPERLET,
				SPLETIVO.DESCRICAO AS SPERLETIVO,
				SPLETIVO.DIASLETIVOS,
				SPLETIVO.CARGAHORARIA,
				STURMADISC.CODDISC,
				STURMADISC.IDHABILITACAOFILIAL,
				SDISCIPLINA.NOME AS NOMEDISCIPLINA,
				SETAPAS.CODETAPA,
				SETAPAS.DESCRICAO,
				SNOTAETAPA.TIPOETAPA,
				SNOTAETAPA.NOTAFALTA,
				SNOTAETAPA.AULASDADAS,
				HR_AULA.CH AS HORAS_AULA,
				SNOTAETAPA.RA
			FROM 
				STURMADISC (NOLOCK)
					LEFT JOIN SDISCIPLINA (NOLOCK) ON 
					SDISCIPLINA.CODDISC = STURMADISC.CODDISC AND
					SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND 
					SDISCIPLINA.CODTIPOCURSO = STURMADISC.CODTIPOCURSO
				LEFT JOIN SFILIAL (NOLOCK) ON
					SFILIAL.CODCOLIGADA = STURMADISC.CODCOLIGADA
					AND SFILIAL.CODFILIAL = STURMADISC.CODFILIAL
				LEFT JOIN SETAPAS (NOLOCK) ON 
					SETAPAS.IDTURMADISC = STURMADISC.IDTURMADISC AND
					SETAPAS.CODCOLIGADA = STURMADISC.CODCOLIGADA
				LEFT JOIN SNOTAETAPA (NOLOCK) ON 
					SNOTAETAPA.IDTURMADISC = SETAPAS.IDTURMADISC AND 
					SNOTAETAPA.CODETAPA = SETAPAS.CODETAPA AND 
					SNOTAETAPA.TIPOETAPA = SETAPAS.TIPOETAPA 
				LEFT JOIN SPLETIVO (NOLOCK) ON
					SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA AND
					SPLETIVO.IDPERLET = STURMADISC.IDPERLET
				
				LEFT JOIN (
					SELECT 
						SDISCGRADE.CH, SHABILITACAOFILIAL.IDHABILITACAOFILIAL, SHABILITACAOFILIAL.CODFILIAL, SDISCGRADE.CODDISC, SHABILITACAOFILIAL.CODCOLIGADA 
					FROM 
						SHABILITACAOFILIAL (NOLOCK)							
						LEFT JOIN SDISCGRADE (NOLOCK) ON
							SDISCGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO AND
							SDISCGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE AND
							SDISCGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND							
							SDISCGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
				) HR_AULA (CH, IDHABILITACAOFILIAL, CODFILIAL, CODDISC, CODCOLIGADA) ON 	
					HR_AULA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND
					HR_AULA.CODFILIAL = STURMADISC.CODFILIAL AND
					HR_AULA.CODDISC = STURMADISC.CODDISC AND
					HR_AULA.CODFILIAL = STURMADISC.CODFILIAL AND
					HR_AULA.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
					
			) ETAPA (
				CODCOLIGADA, 
				DESCJUNTODELEG, 
				DESCDELEGACIA, 
				IDTURMADISC,
				CODFILIAL,
				CODTURMA,
				IDPERLET,
				SPERLETIVO,
				DIASLETIVOS,
				CARGAHORARIA,
				CODDISC,
				IDHABILITACAOFILIAL,
				NOMEDISCIPLINA,
				CODETAPA,
				DESCRICAO,
				TIPOETAPA,
				NOTAFALTA,
				AULASDADAS,
				HORAS_AULA,
				RA
			) ON 
			ETAPA.CODTURMA = SMATRICPL.CODTURMA
			AND ETAPA.RA = SMATRICPL.RA
			AND ETAPA.IDPERLET = SMATRICPL.IDPERLET 
			AND ETAPA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
			AND ETAPA.CODFILIAL = SMATRICPL.CODFILIAL
			AND ETAPA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
		)	

SELECT 
	MANTENEDORA,
	ENDERECO,
	BAIRRO,
	CEP,
	CIDADE,
	TELEFONE,
	DESCJUNTODELEG, 
	DESCDELEGACIA, 
	NIVEL_ENSINO,
	DIASLETIVOS,
	CARGAHORARIA,
	CARGA_HORARIA_CALCULADA = SUM(CASE WHEN CODETAPA IN (10) THEN AULASDADAS END),
	TURNO,
	CODTURMA, 
	NUMALUNO,	
	RA, 
	NOME, 
	CODSTATUS, 
	SITUACAO_MATRICULA,
	CODFILIAL, 
	CODCOLIGADA, 
	IDPERLET, 
	CODHABILITACAO,
	CODCURSOHIST,
	SPERLETIVO,
	NOME_SERIE,

	[TH ARTE] = MAX(CASE WHEN NOMEDISCIPLINA = 'ARTE' THEN HORAS_AULA END),
	[TA ARTE] = MAX(CASE WHEN NOMEDISCIPLINA = 'ARTE' AND CODETAPA IN (10) THEN AULASDADAS END),
	[ARTE] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'ARTE' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,
	
	[TH ARTES] = MAX(CASE WHEN NOMEDISCIPLINA = 'ARTES' THEN HORAS_AULA END),
	[TA ARTES] = MAX(CASE WHEN NOMEDISCIPLINA = 'ARTES' AND CODETAPA IN (10) THEN AULASDADAS END),
	[ARTES] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'ARTES' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,
	
	[TH BIOLOGIA] = MAX(CASE WHEN NOMEDISCIPLINA = 'BIOLOGIA' THEN HORAS_AULA END),
	[TA BIOLOGIA] = MAX(CASE WHEN NOMEDISCIPLINA = 'BIOLOGIA' AND CODETAPA IN (10) THEN AULASDADAS END),
	[BIOLOGIA] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'BIOLOGIA' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,
	
	[TH CIÊNCIAS] = MAX(CASE WHEN NOMEDISCIPLINA = 'CIÊNCIAS' THEN HORAS_AULA END), 
	[TA CIÊNCIAS] = MAX(CASE WHEN NOMEDISCIPLINA = 'CIÊNCIAS' AND CODETAPA IN (10) THEN AULASDADAS END),
	[CIÊNCIAS] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'CIÊNCIAS' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,

	[TH CONCEITO GERAL] = MAX(CASE WHEN NOMEDISCIPLINA = 'CONCEITO GERAL' THEN HORAS_AULA END), 
	[TA CONCEITO GERAL] = MAX(CASE WHEN NOMEDISCIPLINA = 'CONCEITO GERAL' AND CODETAPA IN (10) THEN AULASDADAS END),
	[CONCEITO GERAL] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'CONCEITO GERAL' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,

	[TH EDUCAÇÃO FÍSICA] = MAX(CASE WHEN NOMEDISCIPLINA = 'EDUCAÇÃO FÍSICA' THEN HORAS_AULA END), 
	[TA EDUCAÇÃO FÍSICA] = MAX(CASE WHEN NOMEDISCIPLINA = 'EDUCAÇÃO FÍSICA' AND CODETAPA IN (10) THEN AULASDADAS END),
	[EDUCAÇÃO FÍSICA] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'EDUCAÇÃO FÍSICA' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,

	[TH CONCEITO GERAL] = MAX(CASE WHEN NOMEDISCIPLINA IN ('CONCEITO GERAL') THEN HORAS_AULA END), 
	[TA CONCEITO GERAL] = AVG(CASE WHEN NOMEDISCIPLINA IN ('CONCEITO GERAL') AND CODETAPA IN (10) AND AULASDADAS IS NOT NULL THEN AULASDADAS END), 
	[CONCEITO GERAL] = CASE WHEN (CODCURSOHIST IN ('EF') AND CODHABILITACAO IN (1) ) AND CODSTATUS IN (43,55,51,50) THEN '*' ELSE NULL END,
	
	[TH ENSINO RELIGIOSO] = MAX(CASE WHEN NOMEDISCIPLINA = 'ENSINO RELIGIOSO' THEN HORAS_AULA END), 
	[TA ENSINO RELIGIOSO] = MAX(CASE WHEN NOMEDISCIPLINA = 'ENSINO RELIGIOSO' AND CODETAPA IN (10) THEN AULASDADAS END),
	[ENSINO RELIGIOSO] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'ENSINO RELIGIOSO' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,

	[TH FILOSOFIA] = MAX(CASE WHEN NOMEDISCIPLINA = 'FILOSOFIA' THEN HORAS_AULA END), 
	[TA FILOSOFIA] = MAX(CASE WHEN NOMEDISCIPLINA = 'FILOSOFIA' AND CODETAPA IN (10) THEN AULASDADAS END),
	[FILOSOFIA] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'FILOSOFIA' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,
	
	[TH FÍSICA] = MAX(CASE WHEN NOMEDISCIPLINA = 'FÍSICA' THEN HORAS_AULA END), 
	[TA FÍSICA] = MAX(CASE WHEN NOMEDISCIPLINA = 'FÍSICA' AND CODETAPA IN (10) THEN AULASDADAS END),
	[FÍSICA] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'FÍSICA' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,
	
	[TH GEOGRAFIA] = MAX(CASE WHEN NOMEDISCIPLINA = 'GEOGRAFIA' THEN HORAS_AULA END), 
	[TA GEOGRAFIA] = MAX(CASE WHEN NOMEDISCIPLINA = 'GEOGRAFIA'AND CODETAPA IN (10) THEN AULASDADAS END),
	[GEOGRAFIA] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'GEOGRAFIA' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,
	
	[TH HISTÓRIA] = MAX(CASE WHEN NOMEDISCIPLINA = 'HISTÓRIA' THEN HORAS_AULA END), 
	[TA HISTÓRIA] = MAX(CASE WHEN NOMEDISCIPLINA = 'HISTÓRIA' AND CODETAPA IN (10) THEN AULASDADAS END),
	[HISTÓRIA] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'HISTÓRIA' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,
	
	[TH LÍNGUA ESPANHOLA] = MAX(CASE WHEN NOMEDISCIPLINA = 'LÍNGUA ESPANHOLA' THEN HORAS_AULA END), 
	[TA LÍNGUA ESPANHOLA] = MAX(CASE WHEN NOMEDISCIPLINA = 'LÍNGUA ESPANHOLA' AND CODETAPA IN (10) THEN AULASDADAS END),
	[LÍNGUA ESPANHOLA] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'LÍNGUA ESPANHOLA' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,
	
	[TH LÍNGUA INGLESA] = MAX(CASE WHEN NOMEDISCIPLINA = 'LÍNGUA INGLESA' THEN HORAS_AULA END), 
	[TA LÍNGUA INGLESA] = MAX(CASE WHEN NOMEDISCIPLINA = 'LÍNGUA INGLESA' AND CODETAPA IN (10) THEN AULASDADAS END),
	[LÍNGUA INGLESA] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'LÍNGUA INGLESA' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,
	
	[TH LÍNGUA PORTUGUESA] = MAX(CASE WHEN NOMEDISCIPLINA = 'LÍNGUA PORTUGUESA' THEN HORAS_AULA END), 
	[TA LÍNGUA PORTUGUESA] = MAX(CASE WHEN NOMEDISCIPLINA = 'LÍNGUA PORTUGUESA' AND CODETAPA IN (10) THEN AULASDADAS END),
	[LÍNGUA PORTUGUESA] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'LÍNGUA PORTUGUESA' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,
	
	[TH LITERATURA] = MAX(CASE WHEN NOMEDISCIPLINA = 'LITERATURA' THEN HORAS_AULA END), 
	[TA LITERATURA] = MAX(CASE WHEN NOMEDISCIPLINA = 'LITERATURA' AND CODETAPA IN (10) THEN AULASDADAS END),
	[LITERATURA] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'LITERATURA' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,
	
	[TH MATEMÁTICA] = MAX(CASE WHEN NOMEDISCIPLINA = 'MATEMÁTICA' THEN HORAS_AULA END), 
	[TA MATEMÁTICA] = MAX(CASE WHEN NOMEDISCIPLINA = 'MATEMÁTICA' AND CODETAPA IN (10) THEN AULASDADAS END),
	[MATEMÁTICA] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'MATEMÁTICA' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,
		
	[TH MÚSICA] = MAX(CASE WHEN NOMEDISCIPLINA = 'MÚSICA' THEN HORAS_AULA END), 
	[TA MÚSICA] = MAX(CASE WHEN NOMEDISCIPLINA = 'MÚSICA' AND CODETAPA IN (10) THEN AULASDADAS END),
	[MÚSICA] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'MÚSICA' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,
	
	[TH QUÍMICA] = MAX(CASE WHEN NOMEDISCIPLINA = 'QUÍMICA' THEN HORAS_AULA END), 
	[TA QUÍMICA] = MAX(CASE WHEN NOMEDISCIPLINA = 'QUÍMICA' AND CODETAPA IN (10) THEN AULASDADAS END),
	[QUÍMICA] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'QUÍMICA' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,
	
	[TH SOCIOLOGIA] = MAX(CASE WHEN NOMEDISCIPLINA = 'SOCIOLOGIA' THEN HORAS_AULA END), 
	[TA SOCIOLOGIA] = MAX(CASE WHEN NOMEDISCIPLINA = 'SOCIOLOGIA' AND CODETAPA IN (10) THEN AULASDADAS END),
	[SOCIOLOGIA] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'SOCIOLOGIA' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,

	[TH MÚLTIPLAS LINGUAGENS] = MAX(CASE WHEN NOMEDISCIPLINA = 'MÚLTIPLAS LINGUAGENS' THEN HORAS_AULA END), 
	[TA MÚLTIPLAS LINGUAGENS] = MAX(CASE WHEN NOMEDISCIPLINA = 'MÚLTIPLAS LINGUAGENS' AND CODETAPA IN (10) THEN AULASDADAS END),
	[MÚLTIPLAS LINGUAGENS] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'MÚLTIPLAS LINGUAGENS' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,
		
	[TH REDAÇÃO] = MAX(CASE WHEN NOMEDISCIPLINA = 'REDAÇÃO' THEN HORAS_AULA END), 
	[TA REDAÇÃO] = MAX(CASE WHEN NOMEDISCIPLINA = 'REDAÇÃO' AND CODETAPA IN (10) THEN AULASDADAS END),
	[REDAÇÃO] = CASE WHEN CODSTATUS IN (43,55,51,50) THEN MAX(CASE WHEN NOMEDISCIPLINA = 'REDAÇÃO' AND CODETAPA IN (@CODETAPA_N) THEN (CASE WHEN (NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.70)) THEN CEILING(NOTAFALTA) WHEN ((NOTAFALTA >= (FLOOR(NOTAFALTA) + 0.40)) AND (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.70))) THEN (FLOOR(NOTAFALTA) + 0.50) WHEN (NOTAFALTA < (FLOOR(NOTAFALTA) + 0.40)) THEN FLOOR(NOTAFALTA) ELSE NOTAFALTA END) END) ELSE NULL END,
	
	'ATA DE RESULTADOS FINAIS' AS [NOME TRIMESTRE],
	CODSTATUSRES,		
	SITUACAO_FINAL AS [SITUAÇÃO FINAL]

FROM MAPA_FALTAS 
 
WHERE 
	SPERLETIVO = @SPERLETIVO_M AND 
	CODCOLIGADA = @CODCOLIGADA_N AND
	CODFILIAL = @CODFILIAL_N AND	
	CODTURMA BETWEEN 'EF072' AND 'EF072' /*AND
	CODSTATUS IN (54,55,79,56,50)*/
GROUP BY
	MANTENEDORA,
	ENDERECO,
	BAIRRO,
	CEP,
	CIDADE,
	TELEFONE,
	DESCJUNTODELEG, 
	DESCDELEGACIA, 
	NIVEL_ENSINO,
	DIASLETIVOS,
	CARGAHORARIA,
	TURNO,
	RA, 
	NOME, 
	CODSTATUS, 
	SITUACAO_MATRICULA,
	CODFILIAL, 
	CODCOLIGADA, 
	IDPERLET, 
	CODHABILITACAO,
	CODCURSOHIST,
	SPERLETIVO, 
	CODTURMA,
	NUMALUNO,
	NOME_SERIE,
	CODSTATUSRES,
	SITUACAO_FINAL
ORDER BY 
	CODTURMA, 
	NUMALUNO,
	NOME
