/*
 * Script para o relatório de Inadimplencia
 * @param CODFILIAL				Código da Filial
 * @param DTVENCIMENTO			Data de Vencimentos
 *
 * @author  Marcelo Valvassori Bittencourt
 * @mail	webmaster@pallottism.com.br
 * @version 1.0 bitts 17/04/2017
 * 
 * Solicitante: Estevão (Financeiro)
*/
/**
 - Script Inadimplência
 - Solicitante: Estevão

*/

DECLARE 
	@VJUROS NUMERIC(8,4) = 0.0003,
	@VMULTA NUMERIC(8,4) = 0.02;  


SELECT 
	F.CODFILIAL,
	O.NOME AS CURSO,
	F.RA,
	UPPER(I.NOME) AS ALUNO,
	J.DESCRICAO AS STATUS_MATRICULA,
	K.DESCRICAO AS PERIODO_LETIVO,
	A.IDLAN,
	A.CODCFO,
	UPPER(B.NOMEFANTASIA) AS [RESPONSAVEL FINANCEIRO], 
	B.TELEFONE,
	B.EMAIL,
	E.NOME AS SERVICO,
	D.PARCELA,
	CONVERT(VARCHAR, A.DATAVENCIMENTO, 103) AS [DATA DE VENCIMENTO],
	DATEDIFF(DAY, A.DATAVENCIMENTO, GETDATE()) AS [DIAS VENCIDOS],
	A.VALORORIGINAL AS [VALOR ORIGINAL],
	
	[GRATUIDADE].VALORGRATUIDADE AS [VALOR GRATUIDADE],

	CASE WHEN ([GRATUIDADE].VALORGRATUIDADE IS NOT NULL AND [GRATUIDADE].VALIDADELIMITADA = 1 )
	THEN 
		(A.VALORORIGINAL - ISNULL([GRATUIDADE].VALORGRATUIDADE,0)) * (@VJUROS * DATEDIFF(DAY, A.DATAVENCIMENTO, GETDATE()))
	ELSE
		(A.VALORORIGINAL * (@VJUROS * DATEDIFF(DAY, A.DATAVENCIMENTO, GETDATE())))
	END AS [VALOR JUROS],
	
	CASE WHEN ([GRATUIDADE].VALORGRATUIDADE IS NOT NULL AND [GRATUIDADE].VALIDADELIMITADA = 1 )
	THEN 
		((A.VALORORIGINAL - ISNULL([GRATUIDADE].VALORGRATUIDADE,0)) * @VMULTA) 
	ELSE
		(A.VALORORIGINAL * @VMULTA)
	END AS [VALOR MULTA],
		
	CASE WHEN ([GRATUIDADE].VALORGRATUIDADE IS NOT NULL AND [GRATUIDADE].VALIDADELIMITADA = 1 )
	THEN 
		(A.VALORORIGINAL - ISNULL([GRATUIDADE].VALORGRATUIDADE,0))
		+
		(A.VALORORIGINAL - ISNULL([GRATUIDADE].VALORGRATUIDADE,0)) * (@VJUROS * DATEDIFF(DAY, A.DATAVENCIMENTO, GETDATE()))
		+
		((A.VALORORIGINAL - ISNULL([GRATUIDADE].VALORGRATUIDADE,0)) * @VMULTA) 
	ELSE
		A.VALORORIGINAL
		+
		(A.VALORORIGINAL * (@VJUROS * DATEDIFF(DAY, A.DATAVENCIMENTO, GETDATE()))) 
		+
		(A.VALORORIGINAL * @VMULTA)
	END AS [TOTAL A PAGAR]

FROM
	FLAN AS A (NOLOCK)
		LEFT JOIN FCFO AS B (NOLOCK) ON
			A.CODCOLIGADA = B.CODCOLIGADA AND
			A.CODCFO = B.CODCFO
		LEFT JOIN SLAN AS C (NOLOCK) ON
			A.CODCOLIGADA = C.CODCOLIGADA AND
			A.IDLAN = C.IDLAN
		LEFT JOIN SPARCELA AS D (NOLOCK) ON
			C.CODCOLIGADA = D.CODCOLIGADA AND
			C.IDPARCELA = D.IDPARCELA
		LEFT JOIN SSERVICO AS E (NOLOCK) ON
			D.CODCOLIGADA = E.CODCOLIGADA AND
			D.CODSERVICO = E.CODSERVICO	
		LEFT JOIN SCONTRATO AS F (NOLOCK) ON
			D.CODCOLIGADA = F.CODCOLIGADA AND 
			D.CODCONTRATO = F.CODCONTRATO AND 
			D.IDPERLET = F.IDPERLET AND 
			D.RA = F.RA
		LEFT JOIN SMATRICPL AS G (NOLOCK) ON
			F.CODCOLIGADA = G.CODCOLIGADA AND
			F.CODCONTRATO = F.CODCONTRATO AND
			F.CODFILIAL = G.CODFILIAL AND
			F.RA = G.RA AND
			F.IDPERLET = G.IDPERLET AND
			F.IDHABILITACAOFILIAL = G.IDHABILITACAOFILIAL
		LEFT JOIN SALUNO H (NOLOCK) ON
			G.RA = H.RA AND
			G.CODCOLIGADA = H.CODCOLIGADA
		LEFT JOIN PPESSOA AS I (NOLOCK) ON
			I.CODIGO = H.CODPESSOA
		LEFT JOIN SSTATUS AS J (NOLOCK) ON
			G.CODCOLIGADA = J.CODCOLIGADA AND
			G.CODSTATUS = J.CODSTATUS
		LEFT JOIN SPLETIVO AS K (NOLOCK) ON
			G.CODCOLIGADA = K.CODCOLIGADA AND
			G.CODFILIAL = K.CODFILIAL AND
			G.IDPERLET = K.IDPERLET
		LEFT JOIN FACORDO AS L (NOLOCK) ON 
			L.CODCOLIGADA = A.CODCOLIGADA AND
			L.CODCFO = B.CODCFO
		
		LEFT JOIN SHABILITACAOALUNO AS M (NOLOCK) ON
			M.CODCOLIGADA = A.CODCOLIGADA AND
			M.IDHABILITACAOFILIAL = G.IDHABILITACAOFILIAL AND 
			M.RA = F.RA 
		LEFT JOIN SHABILITACAOFILIAL AS N (NOLOCK) ON
			N.CODCOLIGADA = A.CODCOLIGADA AND
			N.CODFILIAL = A.CODFILIAL AND			
			N.IDHABILITACAOFILIAL = M.IDHABILITACAOFILIAL
			
		LEFT JOIN SCURSO AS O (NOLOCK) ON
			O.CODCOLIGADA = A.CODCOLIGADA AND
			O.CODCURSO = N.CODCURSO 
			
		LEFT JOIN (
			SELECT 
				SBOLSALAN.CODCOLIGADA,
				SBOLSALAN.IDPARCELA,
				SBOLSALAN.IDLAN,
				SBOLSALAN.IDPERLET,
				SUM(SBOLSALAN.VALOR) AS VALORGRATUIDADE,
				SBOLSA.NOME AS [NOME BOLSA],
				CASE WHEN SUM(SBOLSALAN.VALOR) <> 0 THEN 1 ELSE 0 END AS [CONTA GRATUIDADE],
				SBOLSA.VALIDADELIMITADA,
				CASE WHEN SBOLSA.VALIDADELIMITADA = 1 THEN 'ATE O VENCIMENTO' ELSE 'VALIDA APÓS VENCIMENTO' END AS [VALIDADE DA BOLSA]
			FROM 
				SBOLSALAN (NOLOCK) 
				LEFT JOIN SBOLSAPLETIVO (NOLOCK) ON
					SBOLSAPLETIVO.IDPERLET = SBOLSALAN.IDPERLET AND
					SBOLSAPLETIVO.CODCOLIGADA = SBOLSALAN.CODCOLIGADA AND
					SBOLSAPLETIVO.CODBOLSA = SBOLSALAN.CODBOLSA
				LEFT JOIN SBOLSA (NOLOCK) ON
					SBOLSA.CODCOLIGADA = SBOLSALAN.CODCOLIGADA AND
					SBOLSA.CODBOLSA = SBOLSALAN.CODBOLSA 
			GROUP BY 
				SBOLSALAN.CODCOLIGADA,
				SBOLSALAN.IDPARCELA,
				SBOLSALAN.IDLAN,
				SBOLSALAN.IDPERLET,
				SBOLSA.NOME,
				SBOLSA.VALIDADELIMITADA
		) AS [GRATUIDADE] ON
			GRATUIDADE.CODCOLIGADA = A.CODCOLIGADA
			AND GRATUIDADE.IDLAN = A.IDLAN
			AND GRATUIDADE.IDPARCELA = C.IDPARCELA
			AND GRATUIDADE.IDPERLET = K.IDPERLET
WHERE 
	B.IDCFO NOT IN (2358) AND
	F.CODFILIAL = '1' AND
	A.STATUSLAN = 0 AND
	A.DATAVENCIMENTO < GETDATE()
	
