 
/*
PLT029 - Cubo gerencial para escola
	Create By Bitts
	(11/12/2015)
Dados retornados:  
  RA, 
  CODCOLIGADA, 
  CODFILIAL, 
  IDPERLET, 
  DTVENCIMENTO, 
  VALOR_PARCELA, 
  DIASVENCIDOS, 
  PERC_DESCONTO, 
  DATABAIXA, 
  DATACANCELAMENTOBAIXA, 
  VALORBAIXA, 
  VALORORIGINAL, 
  VALORDESCONTO, 
  VALORJUROS, 
  VALORMULTA, 
  PARCELA, 
  COTA, 
  PARCELAINICIAL, 
  PARCELAFINAL, 
  TIPO_DESCONTO  
*/


SELECT
	GCOLIGADA.NOMEFANTASIA AS COLIGADA,
	GCOLIGADA.NOMEFANTASIA AS FILIAL,
	SPLETIVO.CODPERLET,
	SCURSO.NOME AS CURSO,
	SHABILITACAO.NOME AS SERIE,
	SHABILITACAOFILIAL.CODCURSO AS TURMA,
	SSTATUS.DESCRICAO AS STATUS_PERLETIVO,
	STIPOCURSO.NOME  AS TIPOCURSO,
	SALUNO.RA,
	PPESSOA.NOME AS ALUNO,	
	BOLSAS.DTVENCIMENTO,
	BOLSAS.DATABAIXA,
	BOLSAS.DIASVENCIDOS,
	BOLSAS.PARCELA, 
	BOLSAS.COTA, 
	BOLSAS.VALOR_PARCELA, 
	BOLSAS.PERC_DESCONTO, 	
	
	BOLSAS.DATABAIXA, 
	BOLSAS.DATACANCELAMENTOBAIXA, 
	BOLSAS.VALORBAIXA, 
	BOLSAS.VALORORIGINAL, 
	BOLSAS.VALORDESCONTO, 
	BOLSAS.VALORJUROS, 
	BOLSAS.VALORMULTA, 

	BOLSAS.PARCELA,
	BOLSAS.PARCELAINICIAL, 
	BOLSAS.PARCELAFINAL, 
	BOLSAS.VALORBAIXA, 
	BOLSAS.TIPO_DESCONTO,

	1 AS QTDE	
FROM
	SMATRICPL (NOLOCK) 
		LEFT JOIN SALUNO (NOLOCK) ON
			SMATRICPL.CODCOLIGADA				= SALUNO.CODCOLIGADA AND
			SMATRICPL.RA						= SALUNO.RA
			
		LEFT JOIN PPESSOA (NOLOCK) ON
			SALUNO.CODPESSOA					= PPESSOA.CODIGO 
			
		LEFT JOIN SPLETIVO (NOLOCK) ON
			SPLETIVO.CODFILIAL					= SMATRICPL.CODFILIAL AND
			SPLETIVO.CODCOLIGADA				= SMATRICPL.CODCOLIGADA 
					
		LEFT JOIN STIPOCURSO (NOLOCK) ON
			SPLETIVO.CODCOLIGADA				= STIPOCURSO.CODCOLIGADA AND
			SPLETIVO.CODTIPOCURSO				= STIPOCURSO.CODTIPOCURSO
			
		LEFT JOIN SSTATUS (NOLOCK) ON
			SMATRICPL.CODCOLIGADA				= SSTATUS.CODCOLIGADA AND
			SMATRICPL.CODSTATUS					= SSTATUS.CODSTATUS
			
		INNER JOIN SHABILITACAOALUNO (NOLOCK) ON
			SMATRICPL.CODCOLIGADA				= SHABILITACAOALUNO.CODCOLIGADA AND
			SMATRICPL.IDHABILITACAOFILIAL		= SHABILITACAOALUNO.IDHABILITACAOFILIAL AND
			SMATRICPL.RA						= SHABILITACAOALUNO.RA
			
		INNER JOIN SHABILITACAOFILIAL (NOLOCK) ON
			SHABILITACAOALUNO.CODCOLIGADA		= SHABILITACAOFILIAL.CODCOLIGADA AND
			SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
	
		INNER JOIN SGRADE (NOLOCK) ON
			SHABILITACAOFILIAL.CODCOLIGADA		= SGRADE.CODCOLIGADA AND
			SHABILITACAOFILIAL.CODCURSO			= SGRADE.CODCURSO AND
			SHABILITACAOFILIAL.CODHABILITACAO	= SGRADE.CODHABILITACAO AND
			SHABILITACAOFILIAL.CODGRADE			= SGRADE.CODGRADE 
			
		INNER JOIN SHABILITACAO (NOLOCK) ON
			SGRADE.CODCOLIGADA					= SHABILITACAO.CODCOLIGADA AND
			SGRADE.CODHABILITACAO				= SHABILITACAO.CODHABILITACAO AND
			SGRADE.CODCURSO						= SHABILITACAO.CODCURSO
		
		INNER JOIN SCURSO (NOLOCK) ON
			SHABILITACAO.CODCOLIGADA			= SCURSO.CODCOLIGADA AND
			SHABILITACAO.CODCURSO				= SCURSO.CODCURSO
	
		INNER JOIN SFILIAL (NOLOCK) ON
			SHABILITACAOFILIAL.CODCOLIGADA		= SFILIAL.CODCOLIGADA AND
			SHABILITACAOFILIAL.CODFILIAL		= SFILIAL.CODFILIAL 

		INNER JOIN GFILIAL (NOLOCK) ON
			SFILIAL.CODCOLIGADA					= GFILIAL.CODCOLIGADA AND
			SFILIAL.CODFILIAL					= GFILIAL.CODFILIAL
		
		INNER JOIN GCOLIGADA (NOLOCK) ON
			GFILIAL.CODCOLIGADA					= GCOLIGADA.CODCOLIGADA 
		
		LEFT JOIN (
							
			SELECT
				DISTINCT 
				SPARCELA.RA, SBOLSA.CODCOLIGADA, SCONTRATO.CODFILIAL, SCONTRATO.IDPERLET,
				CONVERT(VARCHAR, SPARCELA.DTVENCIMENTO,103) AS DTVENCIMENTO, 
				SPARCELA.VALOR AS VALOR_PARCELA, 
				CASE WHEN ISNULL(DATEDIFF(DAY, SPARCELA.DTVENCIMENTO, FLAN.DATABAIXA),'0') > 0 THEN DATEDIFF(day, SPARCELA.DTVENCIMENTO, FLAN.DATABAIXA) ELSE '0' END AS DIASVENCIDOS,
				CONVERT(VARCHAR, ISNULL(CEILING((SBOLSALAN.VALOR * 100)/ISNULL(SPARCELA.VALOR,SBOLSALAN.VALORBAIXA)), '0'))+'%' AS PERC_DESCONTO,
				
				ISNULL(CONVERT(VARCHAR, FLANBAIXA.DATABAIXA, 103),'') AS DATABAIXA,
				ISNULL(CONVERT(VARCHAR, FLANBAIXA.DATACANCELBAIXA, 103),'') AS DATACANCELAMENTOBAIXA,
		
				ISNULL(CONVERT(VARCHAR, CAST(FLANBAIXA.VALORBAIXA AS DECIMAL(18,2))), '') AS VALORBAIXA,
				ISNULL(CONVERT(VARCHAR, CAST(FLANBAIXA.VALORORIGINAL AS DECIMAL(18,2))), '') AS VALORORIGINAL,
				ISNULL(CONVERT(VARCHAR, CAST(FLANBAIXA.VALORDESCONTO AS DECIMAL(18,2))), '') AS VALORDESCONTO,
				ISNULL(CONVERT(VARCHAR, CAST(FLANBAIXA.VALORJUROS AS DECIMAL(18,2))), '') AS  VALORJUROS,
				ISNULL(CONVERT(VARCHAR, CAST(FLANBAIXA.VALORMULTA AS DECIMAL(18,2))), '') AS VALORMULTA,
				
				SPARCELA.PARCELA, 
				SPARCELA.COTA, 
				SBOLSAALUNO.PARCELAINICIAL, 
				SBOLSAALUNO.PARCELAFINAL,

				SBOLSA.NOME AS TIPO_DESCONTO
			FROM
				SCONTRATO (NOLOCK)
					LEFT JOIN SPARCELA (NOLOCK) ON
						SPARCELA.CODCONTRATO	= SCONTRATO.CODCONTRATO AND  
						SPARCELA.RA				= SCONTRATO.RA AND
						SPARCELA.CODCOLIGADA	= SCONTRATO.CODCOLIGADA AND  
						SPARCELA.IDPERLET		= SCONTRATO.IDPERLET
					LEFT JOIN SSERVICO (NOLOCK) ON
						SSERVICO.CODSERVICO		= SPARCELA.CODSERVICO AND
						SSERVICO.CODCOLIGADA	= SPARCELA.CODCOLIGADA
					LEFT JOIN SLAN (NOLOCK) ON
						SLAN.IDPARCELA			= SPARCELA.IDPARCELA AND
						SLAN.CODCOLIGADA		= SPARCELA.CODCOLIGADA
					LEFT JOIN FLAN (NOLOCK) ON
						FLAN.CODCOLIGADA		= SLAN.CODCOLIGADA AND
						FLAN.IDLAN				= SLAN.IDLAN AND
						FLAN.CODFILIAL			= SCONTRATO.CODFILIAL AND 
						FLAN.PARCELA			= SPARCELA.PARCELA 
					LEFT JOIN FLANBAIXA (NOLOCK) ON
						FLANBAIXA.CODCOLIGADA	= FLAN.CODCOLIGADA AND
						FLANBAIXA.IDLAN			= FLAN.IDLAN
					LEFT JOIN SBOLSALAN (NOLOCK) ON
						SBOLSALAN.IDLAN			= SLAN.IDLAN AND
						SBOLSALAN.IDPARCELA		= SPARCELA.IDPARCELA AND
						SBOLSALAN.IDPERLET		= SCONTRATO.IDPERLET		
					LEFT JOIN SBOLSA (NOLOCK) ON
						SBOLSALAN.CODBOLSA		= SBOLSA.CODBOLSA
					LEFT JOIN SBOLSAALUNO (NOLOCK) ON
						SBOLSAALUNO.IDPERLET	= SCONTRATO.IDPERLET AND
						SBOLSAALUNO.CODCOLIGADA = SCONTRATO.CODCOLIGADA AND
						SBOLSAALUNO.RA			= SCONTRATO.RA AND
						SBOLSAALUNO.CODCONTRATO	= SCONTRATO.CODCONTRATO AND 
						SBOLSAALUNO.CODBOLSA	= SBOLSA.CODBOLSA				
	) BOLSAS (
			RA, 
			CODCOLIGADA, 
			CODFILIAL, 
			IDPERLET, 
			DTVENCIMENTO, 
			VALOR_PARCELA, 
			DIASVENCIDOS, 
			PERC_DESCONTO, 
			DATABAIXA, 
			DATACANCELAMENTOBAIXA, 
			VALORBAIXA, 
			VALORORIGINAL, 
			VALORDESCONTO, 
			VALORJUROS, 
			VALORMULTA, 
			PARCELA, 
			COTA, 
			PARCELAINICIAL, 
			PARCELAFINAL, 
			TIPO_DESCONTO
		) ON
		BOLSAS.RA = SMATRICPL.RA AND
		BOLSAS.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND
		BOLSAS.CODFILIAL = GFILIAL.CODFILIAL AND
		BOLSAS.IDPERLET = SMATRICPL.IDPERLET 
		
WHERE
    SMATRICPL.CODCOLIGADA	= '3' AND
	GFILIAL.CODFILIAL = 3 AND
	--SPLETIVO.CODPERLET	= :PERLETIVO_S AND
	SPLETIVO.CODPERLET		= '2016' 

AND SMATRICPL.RA = '0003413'
	
AND SSTATUS.CODSTATUS IN (39)

ORDER BY SALUNO.RA

