/*
 * PLT045 - Script para listagem do ranking de alunos
 * @param CODFILIAL        Código da Filial
 * @param CODPERLET        Código do Periodo Letivo 
 * @param CODTURMA         Código da Turma
 *
 * @author  Marcelo Valvassori Bittencourt
 * @mail webmaster@pallottism.com.br
 * @version 1.0 bitts 02/12/2016


     SQL para listagem do Ranking de alunos da Institução.

Objetivo: Formação da Média Harmônica:

Descrição da realização do calculo
É realizado o calcula da Média Final de todas as disciplinas de um aluno, conforme formula:

          MEDIA PARCIAL = (NOTA 1 + NOTA 2 + NOTA 3) / 3

          SE ( MEDIA PARCIAL >= 7 ) ENTÃO 
               MEDIA FINAL = MEDIA PARCIAL

          SE ( MEDIA PARCIAL < 7 )  ENTÃO 
               MÉDIA FINAL =  ( ( (NOTA 1 + NOTA 2 + NOTA 3) / 3 ) + NOTA DO EXAME ) / 2

Tomando por base a média final (MF) de cada disciplina, é realizado a soma de todas as médias 
finais, valor esta que e então dividido pelo número total de disciplinas que o aluno frequenta 
no periodo letivo, gerando assim a média aritmética das notas do aluno.

Levando-se em consideração o número de faltas do aluno e gerado um fator depreciativo para
para a média aritmética das notas, seguindo o critério:

           FATOR DEPRECIATIVO = ( (SOMA TOTAL DAS FALTAS DE TODAS AS DISCIPLINAS) * 100 ) / SOMA TOTAL DE AULAS DADAS EM TODAS AS DISCIPLINAS

Para que todos os calculos sejam realizados de forma correto é necessário que todas as notas,
faltas e total de aulas de cada disciplina tenham sido lançadas no sistema.

De posse destes valores é gerado o calculo da média harmônica do aluno, conforme a formula:

          MEDIA HARMONICA = ( MEDIA ARITMETICA - (MEDIA ARITMETICA * FATOR DEPRECIATIVO) )
O critério de desempate é definido pela ordem alfabetica crescente do nome do aluno.


OBS.: Alunos que foram transferidos e por consequência não possuem, uma ou mais, de suas notas 
lançadas no sistema, possuem o mesmo calculo da média final e indice de depreciativo dos demais 
alunos de forma a privilegiar alunos que iniciaram o ano letivo na instituição em detrimento 
dos que não o fizeram.
*/



DECLARE 
	@CDM INT = 3, -- Precisão do calculo (em casas decimais)
	@CODFILIAL INT = 6,
	@CODPERLET VARCHAR(15) = '2016';


WITH HARMONICA AS (
	
	SELECT 
		MA.RA,
		ROUND(
		(SUM(
			CASE WHEN
				N1.NOTA IS NOT NULL AND N2.NOTA IS NOT NULL AND N3.NOTA IS NOT NULL AND ((N1.NOTA + N2.NOTA + N3.NOTA)/3) >= 7    
			THEN 
				ROUND( ((N1.NOTA + N2.NOTA + N3.NOTA)/3), @CDM) 
			WHEN
				N1.NOTA IS NOT NULL AND N2.NOTA IS NOT NULL AND N3.NOTA IS NOT NULL AND ((N1.NOTA + N2.NOTA + N3.NOTA)/3) < 7 AND EX.NOTA IS NOT NULL
			THEN 
				ROUND( ( (((N1.NOTA + N2.NOTA + N3.NOTA)/3) + EX.NOTA)/2 ), @CDM) 
			ELSE NULL END
		) / COUNT(N1.RA)), @CDM) AS [MEDIA NOTAS],
		ROUND(
			CASE WHEN ( (SUM(ISNULL(F1.FALTAS,0) + ISNULL(F2.FALTAS,0) + ISNULL(F3.FALTAS,0))) > 0) THEN
				(((SUM(ISNULL(F1.FALTAS,0) + ISNULL(F2.FALTAS,0) + ISNULL(F3.FALTAS,0))) * 100) / SUM(AULAS.TOTAL))
			ELSE 0 END 
		, @CDM) 
		AS [PERCENTAGEM FALTAS],
		SUM(AULAS.TOTAL) AS [TOTAL DE ALTAS],
		(SUM(ISNULL(F1.FALTAS,0) + ISNULL(F2.FALTAS,0) + ISNULL(F3.FALTAS,0))) AS [TOTAL DE FALTAS],
		
		ROUND(
		(SUM(
			CASE WHEN
				N1.NOTA IS NOT NULL AND N2.NOTA IS NOT NULL AND N3.NOTA IS NOT NULL AND ((N1.NOTA + N2.NOTA + N3.NOTA)/3) >= 7    
			THEN 
				ROUND( ((N1.NOTA + N2.NOTA + N3.NOTA)/3), @CDM) 
			WHEN
				N1.NOTA IS NOT NULL AND N2.NOTA IS NOT NULL AND N3.NOTA IS NOT NULL AND ((N1.NOTA + N2.NOTA + N3.NOTA)/3) < 7 AND EX.NOTA IS NOT NULL
			THEN 
				ROUND( ( (((N1.NOTA + N2.NOTA + N3.NOTA)/3) + EX.NOTA)/2 ), @CDM) 
			ELSE NULL END
		) / COUNT(N1.RA)) -
		((SUM(
			CASE WHEN
				N1.NOTA IS NOT NULL AND N2.NOTA IS NOT NULL AND N3.NOTA IS NOT NULL AND ((N1.NOTA + N2.NOTA + N3.NOTA)/3) >= 7    
			THEN 
				ROUND( ((N1.NOTA + N2.NOTA + N3.NOTA)/3), @CDM) 
			WHEN
				N1.NOTA IS NOT NULL AND N2.NOTA IS NOT NULL AND N3.NOTA IS NOT NULL AND ((N1.NOTA + N2.NOTA + N3.NOTA)/3) < 7 AND EX.NOTA IS NOT NULL
			THEN 
				ROUND( ( (((N1.NOTA + N2.NOTA + N3.NOTA)/3) + EX.NOTA)/2 ), @CDM) 
			ELSE NULL END
		) / COUNT(N1.RA)) * 
		(ROUND(
			CASE WHEN ( (SUM(ISNULL(F1.FALTAS,0) + ISNULL(F2.FALTAS,0) + ISNULL(F3.FALTAS,0))) > 0) THEN
				(((SUM(ISNULL(F1.FALTAS,0) + ISNULL(F2.FALTAS,0) + ISNULL(F3.FALTAS,0))) * 100)/SUM(AULAS.TOTAL)) /100
			ELSE 0 END 
			, @CDM)
		))
		, @CDM) AS [MEDIA HARMONICA]
	FROM 
		SMATRICULA AS MA (NOLOCK) 		
			LEFT JOIN (
				SELECT RA, CONVERT(FLOAT, NOTAFALTA) AS NOTA, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA
				FROM SNOTAETAPA (NOLOCK) 
			) N1 (RA, NOTA, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA) ON
				N1.CODCOLIGADA = MA.CODCOLIGADA AND 
				N1.IDTURMADISC = MA.IDTURMADISC AND
				N1.RA = MA.RA AND 
				N1.CODETAPA = '1' AND
				N1.TIPOETAPA = 'N'
			LEFT JOIN (
				SELECT RA, CONVERT(FLOAT, NOTAFALTA) AS FALTAS, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA 
				FROM SNOTAETAPA (NOLOCK) 
			) F1 (RA, FALTAS, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA) ON
				F1.CODCOLIGADA = MA.CODCOLIGADA AND 
				F1.IDTURMADISC = MA.IDTURMADISC AND
				F1.RA = MA.RA AND 
				F1.CODETAPA = '2' AND
				F1.TIPOETAPA = 'N'
			LEFT JOIN (
				SELECT RA, CONVERT(FLOAT, NOTAFALTA) AS NOTA, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA 
				FROM SNOTAETAPA (NOLOCK) 
			) N2 (RA, NOTA, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA) ON
				N2.CODCOLIGADA = MA.CODCOLIGADA AND 
				N2.IDTURMADISC = MA.IDTURMADISC AND
				N2.RA = MA.RA AND 
				N2.CODETAPA = '3' AND
				N2.TIPOETAPA = 'N'
			LEFT JOIN (
				SELECT RA, CONVERT(FLOAT, NOTAFALTA) AS FALTAS, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA 
				FROM SNOTAETAPA (NOLOCK) 
			) F2 (RA, FALTAS, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA) ON
				F2.CODCOLIGADA = MA.CODCOLIGADA AND 
				F2.IDTURMADISC = MA.IDTURMADISC AND
				F2.RA = MA.RA AND 
				F2.CODETAPA = '4' AND
				F2.TIPOETAPA = 'F'
			LEFT JOIN (
				SELECT RA, CONVERT(FLOAT, NOTAFALTA) AS NOTA, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA 
				FROM SNOTAETAPA (NOLOCK) 
			) N3 (RA, NOTA, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA) ON
				N3.CODCOLIGADA = MA.CODCOLIGADA AND 
				N3.IDTURMADISC = MA.IDTURMADISC AND
				N3.RA = MA.RA AND 
				N3.CODETAPA = '5' AND
				N3.TIPOETAPA = 'N'
			LEFT JOIN (
				SELECT RA, CONVERT(FLOAT, NOTAFALTA) AS FALTAS, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA
				FROM SNOTAETAPA (NOLOCK) 
			) F3 (RA, FALTAS, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA) ON
				F3.CODCOLIGADA = MA.CODCOLIGADA AND 
				F3.IDTURMADISC = MA.IDTURMADISC AND
				F3.RA = MA.RA AND 
				F3.CODETAPA = '6' AND
				F3.TIPOETAPA = 'F'
			LEFT JOIN (
				SELECT RA, CONVERT(FLOAT, NOTAFALTA) AS NOTA, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA
				FROM SNOTAETAPA (NOLOCK) 
			) MD (RA, NOTA, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA) ON
				MD.CODCOLIGADA = MA.CODCOLIGADA AND 
				MD.IDTURMADISC = MA.IDTURMADISC AND
				MD.RA = MA.RA AND 
				MD.CODETAPA = '7' AND
				MD.TIPOETAPA = 'N'
			LEFT JOIN (
				SELECT RA, CONVERT(FLOAT, NOTAFALTA) AS NOTA, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA
				FROM SNOTAETAPA (NOLOCK) 
			) EX (RA, NOTA, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA) ON
				EX.CODCOLIGADA = MA.CODCOLIGADA AND 
				EX.IDTURMADISC = MA.IDTURMADISC AND
				EX.RA = MA.RA AND 
				EX.CODETAPA = '8' AND
				EX.TIPOETAPA = 'N'
			LEFT JOIN (
				SELECT RA, CONVERT(FLOAT, NOTAFALTA) AS NOTA, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA
				FROM SNOTAETAPA (NOLOCK) 
			) MF (RA, NOTA, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA) ON
				MF.CODCOLIGADA = MA.CODCOLIGADA AND 
				MF.IDTURMADISC = MA.IDTURMADISC AND
				MF.RA = MA.RA AND 
				MF.CODETAPA = '10' AND
				MF.TIPOETAPA = 'N'
			LEFT JOIN (
				SELECT RA, CONVERT(INT, AULASDADAS) AS TOTAL, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA 
				FROM SNOTAETAPA (NOLOCK)  
			) AULAS (RA, TOTAL, CODCOLIGADA, IDTURMADISC, CODETAPA, TIPOETAPA) ON
				AULAS.CODCOLIGADA = MA.CODCOLIGADA AND 
				AULAS.IDTURMADISC = MA.IDTURMADISC AND
				AULAS.RA = MA.RA AND 
				AULAS.CODETAPA = '10' AND
				AULAS.TIPOETAPA = 'F'
	WHERE 
		MA.CODSTATUS IN ('17','43','54','64','67','47','23','53','39','50','60','2','44','65','55','19','18','20','34','28','51','40','61') 
		AND MA.RA=N1.RA AND MA.RA=N2.RA AND MA.RA=N3.RA
	GROUP BY MA.RA
)


SELECT 
	ROW_NUMBER() OVER(ORDER BY AR.[MEDIA HARMONICA] DESC) AS [COLOCAÇÃO GERAL],
	ROW_NUMBER() OVER(PARTITION BY MT.CODTURMA ORDER BY AR.[MEDIA HARMONICA] DESC) AS [COLOCAÇÃO TURMA],
	SP.CODPERLET, AR.RA, UPPER(PP.NOME) AS NOME, MT.CODTURMA, AR.[MEDIA HARMONICA] 
FROM 
	HARMONICA AS AR (NOLOCK) 
	LEFT JOIN SALUNO AS AL (NOLOCK) ON 
		AR.RA=AL.RA 
	LEFT JOIN PPESSOA AS PP (NOLOCK) ON 
		AL.CODPESSOA=PP.CODIGO
	LEFT JOIN SMATRICPL AS MT (NOLOCK) ON
		MT.RA=AR.RA
	LEFT JOIN SPLETIVO AS SP (NOLOCK) ON
		MT.IDPERLET = SP.IDPERLET
WHERE 
	SP.CODFILIAL = @CODFILIAL AND
	SP.CODPERLET LIKE '%'+ @CODPERLET +'%'
	
ORDER BY
	AR.[MEDIA HARMONICA] DESC
