/*
	PLT011 - Script de exibição das parcelas de aluno
	Create By Pablo Camilo
	(04/08/2015)
	
	O objetivo deste SQL é buscar todas as parcelas de um determinado período
  1 para verificar se o sistema realmente realizava estas atividades.
	CONCLUSÃO: Nunca essas atividades foram realizadas de forma automatica pelo sistema.
	
	PARAMETROS: IDPERLET
*/

SELECT
	SP.CODCONTRATO, SP.RA, 
	CAST(ISNULL(
		F.VALORORIGINAL 
	,0)	AS DECIMAL(18,2)) AS PARCELA1,
		
    CAST(ISNULL(( 
		SELECT 
			FLAN.VALORORIGINAL 
		FROM
			FLAN 
				INNER JOIN SLAN ON ( FLAN.IDLAN = SLAN.IDLAN AND FLAN.CODCOLIGADA = SLAN.CODCOLIGADA )
				INNER JOIN SPARCELA ON (SPARCELA.CODCOLIGADA = SLAN.CODCOLIGADA AND SPARCELA.IDPARCELA = SLAN.IDPARCELA )
		WHERE  
			SPARCELA.RA = SP.RA AND
			SPARCELA.IDPERLET = SP.IDPERLET AND
			FLAN.CODCFO <>'3000' AND
			SPARCELA.PARCELA = '2' AND
			SPARCELA.CODCONTRATO = SP.CODCONTRATO AND
			SPARCELA.CODSERVICO = SP.CODSERVICO
    ),0) AS DECIMAL(18,2)) AS PARCELA2,
    
    CAST(ISNULL(( 
		SELECT 
			FLAN.VALORORIGINAL 
		FROM 
			FLAN
				INNER JOIN SLAN  ON ( FLAN.IDLAN = SLAN.IDLAN AND FLAN.CODCOLIGADA = SLAN.CODCOLIGADA )
				INNER JOIN SPARCELA  ON (SPARCELA.CODCOLIGADA = SLAN.CODCOLIGADA AND SPARCELA.IDPARCELA = SLAN.IDPARCELA )
		WHERE 
			SPARCELA.RA = SP.RA AND
			SPARCELA.IDPERLET = SP.IDPERLET AND
			FLAN.CODCFO <>'3000' AND
			SPARCELA.PARCELA = '3' AND 
			SPARCELA.CODCONTRATO = SP.CODCONTRATO AND
			SPARCELA.CODSERVICO = SP.CODSERVICO
    ),0) AS DECIMAL(18,2)) AS PARCELA3,
      
	CAST(ISNULL(( 
		SELECT 
			FLAN.VALORORIGINAL 
		FROM
			FLAN
				INNER JOIN SLAN ON ( FLAN.IDLAN = SLAN.IDLAN AND FLAN.CODCOLIGADA = SLAN.CODCOLIGADA )
				INNER JOIN SPARCELA  ON ( SPARCELA.CODCOLIGADA = SLAN.CODCOLIGADA AND SPARCELA.IDPARCELA = SLAN.IDPARCELA )
        WHERE 
			SPARCELA.RA = SP.RA AND 
			SPARCELA.IDPERLET = SP.IDPERLET AND 
			FLAN.CODCFO <>'3000' AND SPARCELA.PARCELA = '4' AND
            SPARCELA.CODCONTRATO = SP.CODCONTRATO AND
            SPARCELA.CODSERVICO = SP.CODSERVICO
    ),0) AS DECIMAL(18,2)) AS PARCELA4,
    
	CAST(ISNULL(( 
		SELECT 
			FLAN.VALORORIGINAL 
		FROM
		    FLAN 
				INNER JOIN SLAN ON ( FLAN.IDLAN = SLAN.IDLAN AND FLAN.CODCOLIGADA = SLAN.CODCOLIGADA )
				INNER JOIN SPARCELA  ON ( SPARCELA.CODCOLIGADA = SLAN.CODCOLIGADA AND SPARCELA.IDPARCELA = SLAN.IDPARCELA )
        WHERE 
			SPARCELA.RA = SP.RA AND
            SPARCELA.IDPERLET = SP.IDPERLET AND
            FLAN.CODCFO <>'3000' AND
            SPARCELA.PARCELA = '5' AND
            SPARCELA.CODCONTRATO = SP.CODCONTRATO AND
            SPARCELA.CODSERVICO = SP.CODSERVICO
    ),0) AS DECIMAL(18,2)) AS PARCELA5,

	CAST(ISNULL(( 
		SELECT 
			FLAN.VALORORIGINAL 
		FROM
			FLAN
				INNER JOIN SLAN ON ( FLAN.IDLAN = SLAN.IDLAN AND FLAN.CODCOLIGADA = SLAN.CODCOLIGADA )
				INNER JOIN SPARCELA  ON ( SPARCELA.CODCOLIGADA = SLAN.CODCOLIGADA AND SPARCELA.IDPARCELA = SLAN.IDPARCELA )
        WHERE  
			SPARCELA.RA = SP.RA AND
			SPARCELA.IDPERLET = SP.IDPERLET AND
            FLAN.CODCFO <>'3000' AND
            SPARCELA.PARCELA = '6' AND
            SPARCELA.CODCONTRATO = SP.CODCONTRATO AND
            SPARCELA.CODSERVICO = SP.CODSERVICO
    ),0) AS DECIMAL(18,2)) AS PARCELA6,             

   CAST(ISNULL(( 
		SELECT 
			FLAN.VALORORIGINAL 
		FROM
          FLAN
			INNER JOIN SLAN ON ( FLAN.IDLAN = SLAN.IDLAN AND FLAN.CODCOLIGADA = SLAN.CODCOLIGADA )
            INNER JOIN SPARCELA  ON (SPARCELA.CODCOLIGADA = SLAN.CODCOLIGADA AND SPARCELA.IDPARCELA = SLAN.IDPARCELA )
        WHERE 
			SPARCELA.RA = SP.RA AND
			SPARCELA.IDPERLET = SP.IDPERLET AND
			FLAN.CODCFO <>'3000' AND
			SPARCELA.PARCELA = '7' AND
			SPARCELA.CODCONTRATO = SP.CODCONTRATO AND
			SPARCELA.CODSERVICO = SP.CODSERVICO
    ),0) AS DECIMAL(18,2)) AS PARCELA7       

FROM 
	FLAN F
		INNER JOIN SLAN S ON ( F.IDLAN = S.IDLAN AND F.CODCOLIGADA = S.CODCOLIGADA )
		INNER JOIN SPARCELA SP ON ( SP.CODCOLIGADA = S.CODCOLIGADA AND SP.IDPARCELA = S.IDPARCELA )

WHERE 
	SP.IDPERLET ='6' AND
	SP.PARCELA ='1'
	
